### ISSUE TITLE
cf deploy issue with new mta plugin 3.2.1 being released

### ISSUE THREAD

**Issue by xbertzx** [cloudfoundry/multiapps-cli-plugin#186] opened 2023-11-16 17:34 UTC
**Description**
Within the last few days our ADO CI/CD Pipeline is now failing with this new mta plugin being released. We haven't updated anything, and we are getting the following error:

"version `GLIBC_2.32' not found"

**Log**
"Searching CF-Community for plugin multiapps...
Plugin multiapps 3.2.1 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from repository CF-Community...
 0 B / 15.91 MiB    0.00%
 15.91 MiB / 15.91 MiB  100.00% 0s
/home/vsts/.cf/plugins/temp1286205103/3113433036: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/vsts/.cf/plugins/temp1286205103/3113433036)
/home/vsts/.cf/plugins/temp1286205103/3113433036: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/vsts/.cf/plugins/temp1286205103/3113433036)
exit status 1
File is not a valid cf CLI plugin binary.
FAILED"

**Source Code in ADO**
steps:
- script: |
    curl -A "" https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    sudo apt-get update
    sudo apt-get install cf8-cli
    cf -v
    cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
    cf install-plugin multiapps -f
    cf api $(fiori_cf_api)
    cf login -u $(fiori_cf_user) -p $(fiori_cf_password) -o $(cf_org) -s $(cf_space)
    cf deploy $(Pipeline.Workspace)/${{ parameters.name }}/$(mta_name).mtar -f
  displayName: "Deploy MTA file to SAP BTP"

**Comment by theghost5800** [comment] 2023-11-17 14:48
Hello @xbertzx , could you please share more details about environment where multiapps cli plugin used to be installed, like OS version, cpu architecture(x86_64, arm and etc).

**Comment by nicolasbender** [comment] 2023-11-17 22:42
I got the same issue. It affects only multiapps>=3.1 on my side, everything below seems fine. This is independent of the cf-cli version, both cf7-cli and cf8-cli are crashing with multiapps>=3.1. I execute these commands in a Docker container with a Debian base image (x86_64). I tested on Debian 11.8 and 12.2.

**Comment by rakinaa2** [comment] 2023-11-17 22:43
Hi I am getting the same issue also when trying to download multiapps plugin. 

The OS version is Ubuntu 22.04.3

`/github/home/.cf/plugins/temp1152128582/920477239: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /github/home/.cf/plugins/temp1152128582/920477239)
/github/home/.cf/plugins/temp1152128582/920477239: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /github/home/.cf/plugins/temp1152128582/920477239)`

**Comment by anksen7** [comment] 2023-11-20 14:44
Hi, I am trying to install the older working version <v3.1 on Ubuntu 20.04 but getting the error .

**Command-** 
cf install-plugin -f https://github.com/cloudfoundry/multiapps-cli-plugin/releases/tag/v3.0.2/multiapps-plugin.linux64 

**Error log**-
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from URL...

 0 B / ?    0.00%
 478 B / ?    4.78% 0s
fork/exec /home/vsts/.cf/plugins/temp421872472/2203977743: exec format error
File is not a valid cf CLI plugin binary.
FAILED

**Comment by theghost5800** [comment] 2023-11-20 14:55
@anksen7 This issue is related to this one https://github.com/cloudfoundry/multiapps-cli-plugin/issues/163 

Other ones which fails with "glibc_<version> not found" are related with used operating systems/docker images which contains older version of glibc. I have make some tests with the following docker images - "ubuntu:22.04" and "debian:12.2" and their glibc version is 2.35 and newer. Could you please try to switch to different base image. 

It will be useful to share which docker images you are using.

**Comment by rakinaa2** [comment] 2023-11-20 17:17
Hi @theghost5800, I am using the GitHub provided runner image. The Operating system is Ubuntu 22.04.

[Ubuntu2204-Readme.md](https://github.com/actions/runner-images/blob/ubuntu22/20231115.7/images/ubuntu/Ubuntu2204-Readme.md)

**Comment by xbertzx** [comment] 2023-11-20 21:05
@rakinaa2 Using Ubuntu 22.04 image fixed our issue. Thank you for this suggestion!

**Comment by marcellourbani** [comment] 2023-12-05 15:15
Same here with docker image mcr.microsoft.com/devcontainers/javascript-node:18-bullseye 
Can't you just link statically?

**Comment by Markus-Schroeder-de** [comment] 2023-12-13 19:16
Hi everybody... sorry that i have not read all open issues before i opened a new one...

The problem is the required Version for GLIBC as 2.32 or 2.34

But Debian 11 (bullseye stable) use Version 2.31...

You could check the installed version with "ldd --version":



maybe you could merge this and the issues: https://github.com/cloudfoundry/multiapps-cli-plugin/issues/192

**Comment by IvanBorislavovDimitrov** [comment] 2024-01-05 14:41
Hello,

The issue is now fixed and version 3.2.2 is now statically linked.
You can install it via:
cf install-plugin -f https://github.com/cloudfoundry/multiapps-cli-plugin/releases/download/v3.2.2/multiapps-plugin.linux64

When the version is merged in the plugins repo: https://github.com/cloudfoundry/cli-plugin-repo/pull/461
you can install it via: cf install-plugin multiapps -f

Thanks and best regards,
Ivan

**Comment by theghost5800** [comment] 2024-01-15 15:52
https://github.com/cloudfoundry/cli-plugin-repo/pull/461 is already merged and `cf install-plugin multiapps -f` command install latest statically linked binary 3.2.2 .

**Closed by theghost5800** 2024-01-15 15:52 UTC
